name: Create Branch

on:
  workflow_dispatch:
    inputs:
      branch_type:
        description: "Type of the new branch (feature, release, fix, hotfix)"
        required: false
        type: choice
        options:
          - feature
          - fix
          - hotfix
          - release
        default: "feature"
      year:
        description: "Year (YY format)"
        required: false
        default: "25"
      quarter:
        description: "Quarter (e.g., 1, 2, 3, 4)"
        required: false
        type: choice
        options:
          - "1"
          - "2"
          - "3"
          - "4"
        default: "2"
      jira_id:
        description: "Jira ID (e.g., ABC-12345)"
        required: false
      description:
        description: "Short description for the branch"
        required: false

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4

      - name: Generate branch name
        id: generate
        run: |
          TYPE="${{ github.event.inputs.branch_type }}"
          YEAR="${{ github.event.inputs.year }}"
          QUARTER="${{ github.event.inputs.quarter }}"
          JIRA="${{ github.event.inputs.jira_id }}"
          DESC="${{ github.event.inputs.description }}"

          DESC_SLUG=""
          if [[ -n "$DESC" ]]; then
            DESC_SLUG=$(echo "$DESC" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
          fi

          if [[ "$TYPE" == "release" ]]; then
            BRANCH_NAME="${TYPE}/${YEAR}.${QUARTER}"
          else
            BRANCH_NAME="$TYPE"
            [ -n "$JIRA" ] && BRANCH_NAME+="/$JIRA"
            BRANCH_NAME+="-${YEAR}.${QUARTER}"
            [ -n "$DESC_SLUG" ] && BRANCH_NAME+="-${DESC_SLUG}"
          fi

          echo "Branch to create: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create new branch
        run: |
          NEW_BRANCH="${{ steps.generate.outputs.branch_name }}"
          BASE="${{ github.ref_name }}"

          echo "Creating branch '$NEW_BRANCH' from '$BASE'..."

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git fetch origin "$BASE"
          git checkout -b "$NEW_BRANCH" "origin/$BASE"
          git push origin "$NEW_BRANCH"

          echo "Branch created: \`$NEW_BRANCH\`" >> $GITHUB_STEP_SUMMARY
